
version: "3.3"

services:
 sa_portal_frontend:
    image: sa_portal_frontend
    container_name: sa_portal_frontend
    restart: always
    build:
      context: .
    ports:
      - "1746:3000"
    env_file:
      - .env.prod
    command: sh -c "cd /app && serve -s build"
    networks:
      - frontend_default

networks:
  frontend_default:
    external: true